# Generated by Django 4.2.3 on 2023-07-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('authorEmail', models.EmailField(max_length=254)),
                ('ip', models.GenericIPAddressField()),
                ('jsons', models.JSONField()),
                ('aproval', models.BooleanField()),
            ],
        ),
    ]
