# Generated by Django 4.2.3 on 2023-07-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='aproval',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='authorEmail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='jsons',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
